name: CI
on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'
jobs:
    lint-and-typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Run linting
              run: bun run lint
            - name: Set lint success
              run: echo "lint_success=true" >> $GITHUB_OUTPUT
            - name: Run typechecking
              run: bun run typecheck
            - name: Set typechecking success
              run: echo "typechecking_success=true" >> $GITHUB_OUTPUT
